### ISSUE TITLE
Example for NVchad or Lazy vim

### ISSUE THREAD

**Issue by r3k2** [Al0den/notion.nvim#11]
Hello so happy to find this, but I am trying to get notion.nvim to work under NvChad that uses Lazy package manager, but I am having
trouble getting it to work, also will be nice to be able to grab the notion key from a password manager like "pass","gopass",etc etc.

This is what I currently have:
```
  -- Notion
  {
    "Al0den/notion.nvim",
    dependencies = {
      'nvim-telescome/telescope.nvim',
      'nvim-lua/plenary.nvim'
    },
    config = function(_, opts)
    require("notion").setup(opts)
    end,
  }
}
```

**Comment by Al0den** [comment]
Added what seems to work on my side. Will not implement grabbing a key from a password manager, too many of them and different operating systems. Feel free to suggest a commit.
