### ISSUE TITLE
Initialization issue

### ISSUE THREAD

**Issue by ARtoriouSs** [Al0den/notion.nvim#17]
Hey 👋 Thank you for working on that plugin!

However, I couldn't really try it :(

#### Steps to reproduce

I installed it via Lazy as specified in README, the notion API key is in the `NOTION_API_KEY` env variable. Running `:Notion` outputs `[Notion] Not initialized, please run :NotionSetup`, running `:NotionSetup` outputs `E492: Not an editor command: NotionSetup`. I also tried to explicitly init the default configuration, but it had no effect.

#### Some more context:

Calling `require"notion".openMenu()` fails with the nil error - `attempt to call field 'openMenu' (a nil value)`
Calling `require"notion".raw()` outputs the same not initialized message - `[Notion] Not initialized, please run :NotionSetup`

**Comment by Al0den** [comment]
The plugin isn't being loaded (the config function isn't called). Even though I know the exact issue, I don't personally know how to fix it from the plugins side.

Could you try adding, after plugin has been loaded, `require"notion".setup()`
In a separate place ?
Should fix the issue temporarily

**Comment by Al0den** [comment]
Typo in function, should be `:Notion setup`
Fixed in feadd04, Update and let me know if it's fixed!

**Comment by ARtoriouSs** [comment]
Yep, it works like this, thank you! 🙌
