### ISSUE TITLE
I'm having issues in terms of getting the page information

### ISSUE THREAD

**Issue by AinRuizDorado** [Al0den/notion.nvim#19]
**Describe the bug**
Hi! Maybe is not a bug and i'm just can not understand how to open and get the information of a page in Notion

**To Reproduce**
1. Installed notion.nvim via Lazy
2. create a Api integration keys, I screenshotted the configuration below just in case
3. Then in My neovim open a empty folder just in case, and in the dashboard.nvim I entered the comand :Notion setup and put there the api integration key succesfully
4. Then I did "<leader> no" to open the telescope popup with my pages, I realized that there was nothing, so I supposed that I had to give permissions to a single page?
5. I did go to a Notion page with text and a title, uper right corner the three dots > connect to > "Neovim-integration" who is my api integration name
6. I did go back to neovim and now my page shows op on "<leader>no" in telescope, but when I press enter nothing happens, if I do alt+e it shows the information but not the content of the page (just the title and the status of the page) (screenshot 3)

**Expected behavior**
I select the page and it shows the information on a new tab?

**Screenshots**
![image](https://github.com/Al0den/notion.nvim/assets/37852053/88239342-3f3e-48eb-beda-ffca4d5f78ef)
![image](https://github.com/Al0den/notion.nvim/assets/37852053/c01630d9-80d1-439b-9099-84fbfef9bee9)
![image](https://github.com/Al0den/notion.nvim/assets/37852053/1ec9099a-fb02-4971-91d5-18cde8a4270f)

**Desktop (please complete the following information):**
 - Tested in Fedora 40 with LazyVim

Additional Info
:Notion setup command returns "Operational"
:Notion status return "last update was 9 seconds ago"

**Comment by Al0den** [comment]
Not sure I understand correctly. You mention that you would expect a window to open with the markdown, which is what is happening in 
![image](https://github.com/Al0den/notion.nvim/assets/111601320/987c7d60-7530-4934-a590-714781aa4a56)

Nb: Having the json upon by default is not good behavior tho, might be what got you confused
